version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/transaction_classifier.db:/app/transaction_classifier.db
    environment:
      - DATABASE_URL=sqlite:///./transaction_classifier.db
    restart: always

  frontend:
    build: ./frontend/Classifier
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/Classifier:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
